name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3'] # Adiciona suporte a múltiplas versões de PHP
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring

      - name: Install dependencies
        run: composer install --no-scripts --no-progress --prefer-dist

      - name: Run tests
        run: vendor/bin/pest
